# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Samuel Sutherland-Dee
email: ssutherlanddee@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome, my name is Samuel Sutherland-Dee and I am currently a student at the University of Bristol.
 I hope to graduate with a degree in Computer Science and pursue a career in technology, perhaps in America.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ssutherlanddee.com" # the base hostname & protocol for your site
twitter_username: SamSDee
github_username:  SamSutherland-Dee

# Build settings
markdown: kramdown
